//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AutoType.rc
//
#define IDDELETE                        3
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDI_TRAY                        108
#define IDR_MAINFRAME                   128
#define IDI_DEACTIVATED                 129
#define IDD_SUGGEST_WORDS               130
#define IDI_NO_SUGGEST                  130
#define IDD_SETTINGS                    132
#define IDD_PASSWORDS                   133
#define IDD_NEWPASSWORD                 134
#define IDD_WORDCHARS                   135
#define IDD_FILEPASSWORD                136
#define IDD_REGISTER                    137
#define IDR_TOOLBAR1                    140
#define IDR_POPUP                       145
#define IDR_SUGGESTIONS                 146
#define IDD_PROP_SUGGESTIONS            146
#define IDD_PROP_DB                     147
#define IDD_UNREG                       148
#define IDC_MYHAND                      149
#define IDD_FONT                        150
#define IDR_POPUP_LIST                  152
#define IDR_POPUP_TRAY                  153
#define IDD_POSITION                    155
#define IDD_APPLICATIONS                156
#define IDD_NEWAPPLICATION              157
#define IDC_CROSSHAIR                   157
#define IDI_WINDOW_CROSSHAIR            158
#define IDI_WINDOW                      159
#define IDI_NO_LEARN                    160
#define IDC_GIVEN                       1020
#define IDC_ADDED                       1021
#define IDC_MAXSUGGESTED                1022
#define IDC_EDIT3                       1023
#define IDC_PROBABILITY                 1023
#define IDC_EDIT4                       1024
#define IDC_SPEED                       1024
#define IDC_EDIT5                       1025
#define IDC_TIMEOUT                     1025
#define IDC_EDIT6                       1026
#define IDC_SCROLLBAR1                  1029
#define IDC_SGIVEN                      1030
#define IDC_SADDED                      1031
#define IDC_SCROLLBAR4                  1032
#define IDC_CHECK1                      1033
#define IDC_SIGNAL                      1033
#define IDC_SCROLLBAR5                  1034
#define IDC_SINGLE                      1034
#define IDC_SCROLLBAR6                  1035
#define IDC_FIXEDPOS                    1035
#define IDC_AUTOSAVE                    1036
#define IDC_BRACKETS                    1036
#define IDC_CASE                        1036
#define IDC_wmCharCount                 1037
#define IDC_SGIVEN2                     1037
#define IDC_DIGITS                      1037
#define IDC_READONLY                    1037
#define IDC_autoTypeCount               1038
#define IDC_CHAR1                       1038
#define IDC_IGNORE_PASSWORDS            1038
#define IDC_DBSIZE                      1039
#define IDC_CHAR2                       1039
#define IDC_ACCESSES                    1040
#define IDC_CHAR3                       1040
#define IDC_ALLOW_NUMBERS               1040
#define IDC_AGE                         1041
#define IDC_CHAR4                       1041
#define IDC_PWLIST                      1042
#define IDC_CHAR5                       1042
#define IDC_NEW                         1043
#define IDC_CHAR6                       1043
#define IDC_DELETE                      1044
#define IDC_CHAR7                       1044
#define IDC_WORD                        1045
#define IDC_CHAR8                       1045
#define IDC_DESCRIPTION                 1046
#define IDC_CHAR9                       1046
#define IDC_WORD1                       1047
#define IDC_CHAR10                      1047
#define IDC_WORD2                       1048
#define IDC_CHAR11                      1048
#define IDC_WORD3                       1049
#define IDC_CHAR12                      1049
#define IDC_WORD4                       1050
#define IDC_CHAR13                      1050
#define IDC_RELAUTO                     1050
#define IDC_WORD5                       1051
#define IDC_CHAR14                      1051
#define IDC_WORD6                       1052
#define IDC_CHAR15                      1052
#define IDC_GIVEN_SPIN                  1052
#define IDC_WORD7                       1053
#define IDC_CHAR16                      1053
#define IDC_ADDED_SPIN                  1053
#define IDC_WORD8                       1054
#define IDC_CHAR17                      1054
#define IDC_MAXSUGGESTED_SPIN           1054
#define IDC_WORD9                       1055
#define IDC_CHAR18                      1055
#define IDC_PROBABILITY_SLIDER          1055
#define IDC_SPEED_SLIDER                1056
#define IDC_RESET                       1056
#define IDC_CHAR19                      1056
#define IDC_AGE_SLIDER                  1057
#define IDC_NAME                        1057
#define IDC_CHAR20                      1057
#define IDC_SIZE_SLIDER                 1058
#define IDC_ID                          1058
#define IDC_REGISTERED                  1059
#define IDC_SPACE                       1060
#define IDR_MAINFRAME1                  1061
#define IDC_HELP2                       1061
#define IDC_NUMPAD                      1061
#define IDC_URL                         1062
#define IDC_TEXT                        1064
#define IDC_VERSION                     1066
#define IDC_REMOVE                      1067
#define IDC_AUTOHIDE                    1069
#define IDC_POSITION                    1070
#define IDC_CARET                       1071
#define IDC_FIXED                       1072
#define IDC_CURSOR                      1073
#define IDC_APPL_LIST                   1074
#define IDC_POSITIVE                    1075
#define IDC_NEGATIVE                    1076
#define IDC_ALL                         1077
#define IDC_FILENAME                    1078
#define IDC_BROWSE                      1079
#define IDC_WINDOW                      1080
#define ID_OPTIONEN_AKTIVIERT           32772
#define ID_OPTIONS_ACTIVATED            32773
#define ID_FILE_SETTINGS                32774
#define ID_OPTIONS_PASSWORDS            32775
#define ID_FILE_CHARS                   32776
#define ID_FILE_PASSWORD                32777
#define ID_HELP_HELP                    32778
#define ID_OPTIONS_COUNTER              32779
#define ID_OPTIONS_COUNTKEYS            32780
#define ID_OPTIONS_REGISTER             32782
#define ID_VIEW_REFRESH                 32787
#define ID_EDIT_DELETE                  32788
#define ID_OPTIONS_COLORS               32789
#define ID_EDIT                         32790
#define ID_EDIT_EDIT                    32791
#define ID_VIEW_SORT_ALPHA              32794
#define ID_VIEW_SORT_OCCURENCES         32795
#define ID_VIEW_SORT_AGE                32796
#define ID_VIEW_SORT_LENGTH             32797
#define ID_FILE_SHORTCUT                32798
#define ID_FILE_READ                    32799
#define ID_OPTIONS_BACKCOLOR            32800
#define ID_OPTIONS_TEXTCOLOR            32802
#define ID_HELP_TEST                    32803
#define ID_SETTINGS_TEST                32804
#define ID_FILE_FIXEDPOS                32805
#define ID_OPTIONS_FONT                 32806
#define ID_OPTIONS_CLIPBOARD            32807
#define ID_APP_RESTORE                  32808
#define ID_OPTIONS_SUGGEST              32810
#define ID_OPTIONS_LEARN                32811
#define ID_POS_FIXED                    32812
#define ID_POS_CARET                    32813
#define ID_POS_CURSOR                   32814
#define ID_FILE_MERGE                   32815
#define ID_OPTIONS_APPLICATIONS         32817
#define IDS_CHARACTERS                  61204
#define IDS_WORDS                       61205
#define IDS_DAYS                        61206
#define IDS_TIMES                       61207
#define IDS_PWERRMSG                    61208
#define IDS_PWERRTITLE                  61209
#define IDS_MFERR                       61210
#define IDS_ILLCHAR                     61211
#define IDS_DLLERR                      61212
#define IDS_PWREPEAT                    61213
#define IDS_PWERRT                      61214
#define IDS_PWERRM                      61215
#define IDS_WRONGPW                     61216
#define IDS_DECYPHER_ERROR              61216
#define IDS_SPY_HOOK_NOT_SET            61217
#define IDS_THANKS                      61218
#define IDS_INVALID_ID                  61219
#define IDS_REGISTERED                  61220
#define IDS_WORD                        61221
#define IDS_OCCURENCES                  61222
#define IDS_AGE                         61223
#define IDS_FORECOLOR                   61224
#define IDS_BACKCOLOR                   61225
#define IDS_TOOLONG                     61226
#define IDS_DUPE                        61227
#define IDS_SHORTCUT_FILTERS            61228
#define IDS_TEXT_FILTERS                61229
#define IDS_UNREG_LIMITS                61230
#define IDS_UNREG_AGE                   61230
#define IDS_EXE_FILTERS                 61230
#define IDS_UNREG_SIZE                  61231
#define IDS_SETTINGS                    61232
#define IDS_URL                         61233
#define IDS_LICENSED                    61234
#define IDS_LANGUAGE                    61235
#define IDS_INVALID_REGKEY              61236
#define IDS_BROKEN_EXE                  61237
#define IDS_FROZEN                      61238
#define IDS_NO_LEARN                    61238
#define IDS_OPENDOC_ERROR               61239
#define IDS_READ_ERROR                  61240
#define IDS_VERSION_ERROR               61241
#define IDS_VOCABULARY_FILTERS          61242
#define IDS_NO_SUGGEST                  61243
#define IDS_DEACTIVATED                 61244

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
